theme: jekyll-theme-minimal
title: ATATC
logo: /assets/img/logo.png
description: Autonomous Racing; Medical Image Processing; Full Stack Developer
show_downloads: true
github:
  zip_url: https://projectneura.org/resume/terry.fu.zip
  tar_url: https://projectneura.org/resume/terry.fu.tar.gz
